name: 'prajwalkoirala-com'
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v2
    - run: go build ./AppEngine/prajwalkoirala-com/main.go
    - run: go run ./AppEngine/prajwalkoirala-com/main &
